import assert from 'node:assert/strict'
import { readFile, mkdir } from 'node:fs/promises'
import { createRequire } from 'node:module'
import { initializeTestEnvironment } from '@firebase/rules-unit-testing'

if (process.env.FIRESTORE_EMULATOR_HOST !== '127.0.0.1:8086') throw new Error('Emulator required')
const require = createRequire(import.meta.url)
const { chromium } = require(process.env.PLAYWRIGHT_PACKAGE || 'playwright')
const { expect } = require(process.env.PLAYWRIGHT_PACKAGE ? `${process.env.PLAYWRIGHT_PACKAGE}/test` : 'playwright/test')
const env = await initializeTestEnvironment({ projectId: 'demo-yumiko-qa', firestore: { host: '127.0.0.1', port: 8086, rules: await readFile('firestore.rules', 'utf8') } })
const signup = await fetch('http://127.0.0.1:9096/identitytoolkit.googleapis.com/v1/accounts:signUp?key=fake-emulator-key', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: 'qa@example.test', password: 'OnlyForEmulator123!', returnSecureToken: true }) }).then(response => response.json())
if (!signup.localId) throw new Error(JSON.stringify(signup))
const now = new Date()
await env.withSecurityRulesDisabled(async context => {
  const db = context.firestore()
  const seed = {
    [`users/${signup.localId}`]: { companyId: 'co', branchId: 'main', email: 'qa@example.test', displayName: 'QA Cashier', role: 'owner', isActive: true, permissions: [] },
    'companies/co': { name: 'QA Store', status: 'active' },
    'branches/main': { companyId: 'co', name: 'Yumiko Wig Studio QA', code: '00', isMainBranch: true, status: 'active' },
    'branches/second': { companyId: 'co', name: 'QA Second Branch', code: '01', isMainBranch: false, status: 'active' },
    'system_settings/co': { companyId: 'co', nameTh: 'ร้านทดสอบ', allowNegativeStock: false },
    'system_settings/co_tax': { companyId: 'co' },
    'products/p': { companyId: 'co', branchId: 'main', name: 'สินค้าทดสอบ', sku: 'QA001', sellingPrice: 100, costPrice: 20, isActive: true, stockQty: 10, minStockAlert: 2, images: [], createdAt: now },
    'services/svc': { companyId: 'co', branchId: 'main', sourceBranchId: 'main', catalogScope: 'shared', visibleBranchIds: ['main', 'second'], code: 'SVC-QA', name: 'บริการทดสอบ', category: 'บริการทั่วไป', price: 500, duration: 30, taxType: 'vat', isActive: true, status: 'active', createdAt: now, updatedAt: now },
    'inventory/p_main': { companyId: 'co', branchId: 'main', productId: 'p', quantity: 10 },
    'customers/customer': { companyId: 'co', branchId: 'main', firstName: 'ทดสอบ', lastName: 'ลูกค้า', phone: '0800000000', customerId: 'C-QA001', createdAt: now },
    'deposits/dep': { companyId: 'co', branchId: 'main', depositNo: 'DEP-QA-001', customerId: 'customer', customerName: 'ทดสอบ ลูกค้า', totalAmount: 100, depositAmount: 30, paidAmount: 50, remainingAmount: 50, status: 'deposited', items: [{ productId: 'p', name: 'สินค้าทดสอบ', quantity: 1, unitPrice: 100, total: 100 }], paymentHistory: [{ id: 'initial', amount: 30, method: 'cash', confirmed: true, receivedAt: now }, { id: 'second', amount: 20, method: 'cash', confirmed: true, receivedAt: now }], createdAt: now },
  }
  for (const [path, data] of Object.entries(seed)) await db.doc(path).set(data)
})
await mkdir('test-results', { recursive: true })
const browser = await chromium.launch({ headless: true, channel: 'chrome' })
const page = await browser.newPage({ viewport: { width: 1440, height: 960 } })
const errors = []
page.on('pageerror', error => errors.push(error.message))
page.on('console', message => {
  if (message.type() === 'error' && /Maximum update depth|Error loading branches|permission.denied/i.test(message.text())) errors.push(message.text())
})
page.on('dialog', dialog => dialog.accept())
try {
  await page.goto('http://localhost:3106/login')
  await page.locator('input[type=email]').fill('qa@example.test')
  await page.locator('input[type=password]').fill('OnlyForEmulator123!')
  await page.locator('button[type=submit]').click()
  await page.waitForURL('**/dashboard', { timeout: 60000 })
  await page.goto('http://localhost:3106/products')
  await page.getByRole('button', { name: 'รายการบริการ (1)' }).click()
  await page.getByText('บริการทดสอบ', { exact: true }).waitFor()
  await page.getByRole('button', { name: 'แก้ไขบริการ บริการทดสอบ' }).click()
  const serviceDialog = page.getByRole('dialog', { name: 'แก้ไขบริการ' })
  await serviceDialog.getByLabel(/ราคา/).fill('750.50')
  await serviceDialog.getByLabel('หมายเหตุ').fill('แก้ไขจากหน้ารายการบริการ')
  await serviceDialog.getByRole('button', { name: 'บันทึกการแก้ไข' }).click()
  await expect(serviceDialog).toBeHidden()
  await expect(page.getByText('฿750.50', { exact: true })).toBeVisible()
  let editedService
  await env.withSecurityRulesDisabled(async context => { editedService = await context.firestore().doc('services/svc').get() })
  assert.equal(editedService.data().price, 750.5)
  assert.equal(editedService.data().catalogScope, 'shared', 'Editing must preserve the central catalog scope')
  await page.screenshot({ path: 'test-results/service-edit.png', fullPage: true })
  await page.goto('http://localhost:3106/pos')
  await page.getByText('สินค้าทดสอบ', { exact: true }).first().click()
  await page.getByRole('button', { name: 'พักบิล', exact: true }).click()
  await page.getByRole('button', { name: 'บิลที่พัก (1)' }).click()
  await page.getByRole('button', { name: /ลูกค้าทั่วไป/ }).last().click()
  await page.waitForTimeout(500)
  assert.equal(await page.locator('#pos-cart-panel').getByText('สินค้าทดสอบ', { exact: true }).count(), 1)
  await page.reload()
  await page.getByRole('button', { name: 'เรียกคืน', exact: true }).click()
  assert.equal(await page.locator('#pos-cart-panel').getByText('สินค้าทดสอบ', { exact: true }).count(), 1)
  await page.screenshot({ path: 'test-results/pos-desktop.png', fullPage: true })
  await page.getByLabel('ค้นหาทั้งระบบ').fill('0800')
  await page.getByRole('link', { name: /ทดสอบ ลูกค้า/ }).first().waitFor()
  await page.getByLabel('ค้นหาทั้งระบบ').fill('DEP-QA')
  await page.getByRole('link', { name: /DEP-QA-001/ }).click()
  await page.waitForURL('**/deposits?q=*')
  await page.getByRole('link', { name: 'เปิดบิลปิดมัดจำ' }).click()
  await page.waitForURL('**/pos?depositId=dep')
  await page.getByText(/โหลด DEP-QA-001 แล้ว/).first().waitFor()
  await page.getByRole('button', { name: /ไปชำระเงิน/ }).first().click()
  await page.getByText(/หักมัดจำ/).first().waitFor()
  await page.screenshot({ path: 'test-results/deposit-checkout.png', fullPage: true })
  await page.keyboard.press('Escape')
  await page.goto('http://localhost:3106/reports')
  await page.getByText('รับสุทธิ', { exact: false }).first().waitFor()
  await page.screenshot({ path: 'test-results/reports-desktop.png', fullPage: true })
  await page.goto('http://localhost:3106/accounting')
  await page.getByRole('heading', { name: 'บัญชีการเงิน' }).waitFor()
  await page.getByText('เงินรับสุทธิ', { exact: true }).waitFor()
  await page.screenshot({ path: 'test-results/accounting-desktop.png', fullPage: true })
  await page.goto('http://localhost:3106/activity-log')
  await page.getByRole('heading', { name: 'บันทึกกิจกรรม' }).waitFor()
  await page.screenshot({ path: 'test-results/activity-log.png', fullPage: true })
  const branchSelector = page.getByRole('banner').getByTitle('เลือกสาขาที่ต้องการดู')
  await branchSelector.selectOption('second')
  await page.locator('a[href="/pos"]').first().click()
  await page.waitForURL('**/pos')
  await page.getByRole('button', { name: 'พักบิล', exact: true }).waitFor()
  await page.waitForTimeout(1000)
  assert.equal(await branchSelector.inputValue(), 'second', 'Navigating must retain the selected branch')
  await page.locator('a[href="/accounting"]').first().click()
  await page.waitForURL('**/accounting')
  await page.getByRole('heading', { name: 'บัญชีการเงิน' }).waitFor()
  await page.waitForTimeout(1000)
  assert.equal(await branchSelector.inputValue(), 'second', 'Accounting must retain the selected branch')
  await page.addInitScript(() => {
    window.branchValuesSeen = []
    new MutationObserver(() => {
      const value = document.querySelector('header select[title="เลือกสาขาที่ต้องการดู"]')?.value
      if (value) window.branchValuesSeen.push(value)
    }).observe(document, { childList: true, subtree: true })
  })
  await page.reload()
  await expect(branchSelector).toHaveValue('second')
  assert.equal(await page.evaluate(() => window.branchValuesSeen.includes('main')), false, 'Reload must not render the home branch while restoring the preference')
  await page.goto('http://localhost:3106/pos')
  await expect(branchSelector).toHaveValue('second')
  await page.getByRole('button', { name: 'พักบิล', exact: true }).waitFor()
  await env.withSecurityRulesDisabled(context => context.firestore().doc(`users/${signup.localId}`).update({ displayName: 'QA Cashier Updated' }))
  await page.getByRole('banner').getByText('QA Cashier Updated', { exact: true }).waitFor()
  await expect(branchSelector).toHaveValue('second')
  await page.screenshot({ path: 'test-results/branch-restored-desktop.png', fullPage: true })
  await env.withSecurityRulesDisabled(context => context.firestore().doc('branches/second').update({ status: 'archived' }))
  await page.getByRole('banner').getByText('Yumiko Wig Studio QA', { exact: true }).waitFor()
  await page.reload()
  await page.getByRole('banner').getByText('Yumiko Wig Studio QA', { exact: true }).waitFor()
  await env.withSecurityRulesDisabled(context => context.firestore().doc('branches/second').update({ status: 'active' }))
  await expect(branchSelector).toHaveValue('main')
  await branchSelector.selectOption('second')
  await env.withSecurityRulesDisabled(context => context.firestore().doc(`users/${signup.localId}`).update({ role: 'sales' }))
  await page.getByRole('banner').getByText('sales', { exact: true }).waitFor()
  await page.getByRole('banner').getByText('Yumiko Wig Studio QA', { exact: true }).waitFor()
  assert.equal(await branchSelector.count(), 0, 'Restricted staff cannot switch branches')
  await page.reload()
  await page.getByRole('banner').getByText('Yumiko Wig Studio QA', { exact: true }).waitFor()
  await env.withSecurityRulesDisabled(context => context.firestore().doc('branches/main').update({ status: 'archived' }))
  await page.getByRole('alert').getByText(/ไม่พบสาขาที่เปิดใช้งาน/).waitFor()
  assert.equal(await page.getByRole('button', { name: 'พักบิล', exact: true }).count(), 0, 'Unavailable assigned branch must block checkout, not use another branch')
  await page.screenshot({ path: 'test-results/branch-unavailable.png', fullPage: true })
  await env.withSecurityRulesDisabled(context => context.firestore().doc('branches/main').update({ status: 'active' }))
  await page.getByRole('banner').getByText('Yumiko Wig Studio QA', { exact: true }).waitFor()
  await env.withSecurityRulesDisabled(context => context.firestore().doc(`users/${signup.localId}`).update({ role: 'owner' }))
  await expect(branchSelector).toHaveValue('main')
  await branchSelector.selectOption('main')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('http://localhost:3106/pos')
  await page.getByRole('button', { name: 'พักบิล', exact: true }).waitFor()
  await page.getByText('สินค้าทดสอบ', { exact: true }).first().waitFor()
  await page.getByRole('button', { name: 'เรียกคืน', exact: true }).click()
  assert.equal(await page.locator('#pos-cart-panel').getByText('สินค้าทดสอบ', { exact: true }).count(), 1)
  await page.screenshot({ path: 'test-results/pos-mobile.png', fullPage: true })
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1), false, 'Mobile page must not overflow horizontally')
  assert.deepEqual(errors, [])
  console.log('UI smoke passed: service edit, park/recover, global search, deposit checkout, reports, accounting, activity log, branch navigation/reload/profile updates/archived branch/role restrictions, mobile layout')
} finally {
  await browser.close()
  await env.cleanup()
}
